variable "project_name" {}
variable "region" {}
variable "role_ecs_arn" {}
variable "postgres_db" {}
variable "postgres_user" {}
variable "postgres_password" {}
variable "postgres_port" {}
variable "postgres_host" {}
variable "docker_image_airflow" {}
variable "docker_image_redis" {}
variable "private_subnet_group_id1" {}
variable "private_subnet_group_id2" {}
variable "webserver_sg" {}
variable "redis_sg" {}
variable "scheduler_sg" {}
variable "worker_sg" {}
variable "flower_sg" {}
variable "alb_webserver_target_group" {}
variable "alb_redis_target_group" {}
variable "redis_host" {}