variable "project_name" {}
variable "region" {}
variable "role_ecs_arn" {}
variable "postgres_db" {}
variable "postgres_user" {}
variable "postgres_password" {}
variable "postgres_port" {}
variable "postgres_host" {}
variable "docker_image_airflow" {}
variable "private_subnet_group_id1" {}
variable "private_subnet_group_id2" {}
variable "webserver_sg" {}
variable "redis_sg" {}
variable "scheduler_sg" {}
variable "worker_sg" {}
variable "flower_sg" {}
variable "alb_webserver_target_group" {}
variable "airflow_efs_id" {}
variable "airflow_efs_access_id" {}
variable "rds_data_host" {}
variable "discovery_service_redis_arn" {}