variable "aws_region" {}
variable "aws_profile" {}
variable "project_name" {}
variable "postgres_port" {}
variable "postgres_user" {}
variable "postgres_password" {}
variable "postgres_db" {}
variable "docker_image_redis" {}
variable "docker_image_airflow" {}
